train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./data/DIV2K_train_HR
      repeat: 20 
  wrapper:
    name: sr-implicit-downsampled-fast
    args:
      inp_size: 128
      scale_max: 4
      augment: true
      # additional_augment : True
      ranges : [-1, 1]
  batch_size: 64

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./data/DIV2K_valid_HR
  wrapper:
      name: sr-implicit-downsampled-fast
      args:
        scale_min: 4
        scale_max: 4
        ranges : [-1, 1]
  batch_size: 1
eval_type: div2k-4
eval_bsize: 500

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: sofono
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    width: 256
    T : 3
    ranges : [-1, 1]
    local_branch : Conv
    init_s : 0.0

loss :
  alpha: 1

optimizer:
  name: adam
  args:
    lr: 4.e-5
  s_lr : 1.e-4
epoch_max: 1050

warmup_step_lr:
  multiplier: 10
  total_epoch: 50

epoch_val: 250
epoch_save: 250

save_name : edsr-baseline-SoFoNO
save_dir : ./save